version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: devit-postgres-prod
    environment:
      POSTGRES_DB: devit
      POSTGRES_USER: devit
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - devit-network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: devit-redis-prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - devit-network
    restart: unless-stopped

  # MinIO S3-compatible storage
  minio:
    image: minio/minio:latest
    container_name: devit-minio-prod
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - devit-network
    restart: unless-stopped

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: devit-backend-prod
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://devit:${POSTGRES_PASSWORD}@postgres:5432/devit
      - REDIS_URL=redis://redis:6379
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - RUST_LOG=info
      - DOMAIN=devit.dev
    depends_on:
      - postgres
      - redis
      - minio
    networks:
      - devit-network
    restart: unless-stopped

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: devit-frontend-prod
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.devit.dev
      - NEXT_PUBLIC_WS_URL=wss://api.devit.dev
      - NEXT_PUBLIC_DOMAIN=devit.dev
      - NEXTAUTH_URL=https://devit.dev
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - backend
    networks:
      - devit-network
    restart: unless-stopped

  # Nginx Reverse Proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: devit-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./infrastructure/nginx/devit.dev.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/devit.dev.crt:/etc/ssl/certs/devit.dev.crt
      - ./ssl/devit.dev.key:/etc/ssl/private/devit.dev.key
    depends_on:
      - frontend
      - backend
    networks:
      - devit-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  minio_data:

networks:
  devit-network:
    driver: bridge
