version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: devit-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: devit
      MYSQL_USER: devit
      MYSQL_PASSWORD: devit_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
